"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.extractResult = void 0;
const fs_1 = require("fs");
const github = __importStar(require("@actions/github"));
function getCommit() {
    if (github.context.payload.head_commit) {
        return github.context.payload.head_commit;
    }
    const pr = github.context.payload.pull_request;
    if (!pr) {
        throw new Error(`No commit information is found in payload: ${JSON.stringify(github.context.payload, null, 2)}`);
    }
    // On pull_request hook, head_commit is not available
    const message = pr.title;
    const id = pr.head.sha;
    const timestamp = pr.head.repo.updated_at;
    const url = `${pr.html_url}/commits/${id}`;
    const name = pr.head.user.login;
    const user = {
        name,
        username: name, // XXX: Fallback, not correct
    };
    return {
        author: user,
        committer: user,
        id,
        message,
        timestamp,
        url,
    };
}
function extractGoogleCppResult(output) {
    let json;
    try {
        json = JSON.parse(output);
    }
    catch (err) {
        throw new Error(`Output file for 'googlecpp' must be JSON file generated by --benchmark_format=json option: ${err.message}`);
    }
    const host_name = json.context.host_name;
    const result = json.benchmarks.map((b) => {
        const name = b.name;
        const value = b.real_time;
        const unit = b.time_unit + '/iter';
        const repetitions = b.repetitions;
        const extra = `iterations: ${b.iterations}\ncpu: ${b.cpu_time} ${b.time_unit}\nthreads: ${b.threads}`;
        return { name, value, unit, repetitions, extra };
    });
    return { host_name: host_name, result: result };
}
async function extractResult(config) {
    const output = await fs_1.promises.readFile(config.outputFilePath, 'utf8');
    const extracted = extractGoogleCppResult(output);
    const host_name = extracted.host_name;
    const benches = extracted.result;
    if (benches.length === 0) {
        throw new Error(`No benchmark result was found in ${config.outputFilePath}. Benchmark output was '${output}'`);
    }
    const commit = getCommit();
    return {
        host_name,
        commit,
        date: Date.now(),
        benches,
    };
}
exports.extractResult = extractResult;
